In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [5]:
dataset = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-'+
          'databases/iris/iris.data',sep= ',', header= None)

In [7]:
data = dataset.iloc[:,:]

In [8]:
data.head()

0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [9]:
data.isnull().sum()

0    0
1    0
2    0
3    0
4    0
dtype: int64

In [16]:
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

In [17]:
print(x[:5,:])
print(y[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']


In [19]:
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)

In [25]:
import numpy as np
np.unique(y)

array([0, 1, 2])

In [26]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.3, random_state = 0)

In [29]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier = classifier.fit(x_train, y_train)
predict = classifier.predict(x_test)

In [30]:
confusion_matrix(y_test,predict)

array([[16,  0,  0],
       [ 0, 17,  1],
       [ 0,  0, 11]])

In [32]:
accuracy_score(y_test, predict)

0.9777777777777777

In [35]:
print(classification_report(y_test, predict))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.94      0.97        18
           2       0.92      1.00      0.96        11

    accuracy                           0.98        45
   macro avg       0.97      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45

